interfaces:
  - name: notification
    plugins:
      - name: email
        methods:
          - Send
          - Delete
          - Update

  - name: payment
    plugins:
      - name: stripe
        methods:
          - Charge
          - Refund
          - Status 